platform :osx, '10.14'

target 'Server_lab4' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Swifter'
  pod 'BigInt'
  pod 'SwiftyJSON'
  pod 'KeychainSwift'
  pod 'SendGrid', :git => 'https://github.com/scottkawai/sendgrid-swift.git'
  
end
